name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
          secrets: |
            PHONE_ENV
            WECOM_WEBHOOK
        env:
          PHONE_ENV: ${{ secrets.PHONE }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}